### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by yamsergey** [berryamin/playbook-dev-tools#3]
Looks like it's the last active fork :)

If anyone still supports it I have a couple of questions:

- `bzip2` URL seems to be broken and `http://bzip.org` doesn't serve needed distribution anymore. I've solved it by replacing `http://bzip.org` with `https://fossies.org/linux/misc/`. Should I open a PR?
- I've installed `git` on the device, but most of the time it returns me an exception like `wrong line 5 in .git/config` and the config is generated by git itself. But sometimes it works. I don't have any clue why is it happens. Any idea?
- Did anyone try to compile Vim with python support?

**Comment by berryamin** [comment]
Hey hello Sir !

  I'm so glad about your post. Yep fork is still active ! I hope to "release" gnutls soon.. but on Mac OS it's still not working, but very close to it. I will probably try the same on Linux. Gnutls would enable many apps, the first I think is taskwarrior sync over ssl.

   Yes sure open a PR for bzip2, I'll take care.

   About git, I know, I hit the same kind of issues, it sometimes work, sometime it breaks. I think some signals are handled in a special way on QNX, but don't know exactly what happens.

   Python on bb10 seems a very difficult task .. I tried to compile something more recent than the stock Python once or twice but no success so far. Maybe a Python expert would succeed, and it would be great.

   Thank you for the feedback :)

Olivier

**Comment by yamsergey** [comment]
Wow :) ok, I will open the PR. Also I think that it will be super useful to dockerize the build process to avoid all this "doesn't work on Mac OS" - I can take care about it.

P.S.

I did some attempts to build the vim with python and it doesn't looks like a feasible task so far. Frankly speaking I'm not sure that BB10 is worth to spend time on it only as an education :(

**Comment by yamsergey** [comment]
@berryamin can you give me write permissions, so I can create a branch and the PR

**Comment by berryamin** [comment]
@yamsergey : sure, many appologizes about the delay, did not see your feedback due to bad email destination .. Write permissions now granted (you have to accept the invitation)
